language: go

matrix:
  fast_finish: true
  include:
    - go: 1.13.x
    - go: 1.14.x
    - go: master

before_install:
  - go get -v ./...

install:
  - go test -v -benchmem -test.bench=".*" -coverprofile=coverage.txt -covermode=atomic  ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)